# -----------------------------------------------------------------------------
# 敏感配置信息模板 (config.secret.template.yaml)
# -----------------------------------------------------------------------------
#
# 使用说明:
# 1. 将此文件复制为 `config.secret.yaml`
# 2. 在新文件中填入您的实际敏感信息
# 3. 确保 config.secret.yaml 已被添加到 .gitignore 中，不会被提交到版本控制系统
#
# 此文件包含所有需要保密的配置项，如API密钥、密码、密钥等

# -----------------------------------------------------------------------------
# 邮件账户配置
# -----------------------------------------------------------------------------
email:
  username: "your_email@example.com"  # 替换为您的邮箱用户名
  password: "your_email_password"      # 替换为您的邮箱密码或应用专用密码

# -----------------------------------------------------------------------------
# 钉钉机器人配置
# -----------------------------------------------------------------------------
dingtalk:
  robots:
    - name: "测试机器人"
      webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=your_access_token"
      secret: "your_secret"  # 钉钉机器人的签名密钥（如果启用了加签安全设置）
    
    
    # 可以根据需要添加更多机器人

# -----------------------------------------------------------------------------
# AI分析器API密钥配置
# -----------------------------------------------------------------------------
ai_analyzer:
  # API密钥配置
  # 您可以配置多个模型的API密钥，系统会根据active_model_profile选择使用哪个
  
  # 模型Profile对应的API密钥
  profile_api_keys:
    qwen: "your_qwen_api_key"       # 阿里云通义千问API密钥
    grok: "your_grok_api_key"       # Grok (X.AI) API密钥



# -----------------------------------------------------------------------------
# 管理后台认证配置
# -----------------------------------------------------------------------------
admin:
  username: "admin"           # 管理员用户名
  password: "strong_password" # 管理员密码（建议使用强密码）

# -----------------------------------------------------------------------------
# 其他敏感配置
# -----------------------------------------------------------------------------
# 如有其他需要保密的配置项，请在此处添加 