# 邮件通知配置
email:
  enabled: true  # 启用邮件通知功能
  smtp_server: "smtp.gmail.com"  # Gmail SMTP服务器地址
  smtp_port: 587  # Gmail SMTP端口（TLS）
  use_tls: true  # 启用TLS加密
  sender: "cloudnetworkspy@gmail.com"  # 您的Gmail邮箱地址
  recipients: ["21586750@qq.com","tianxiang.btx@alibaba-inc.com"]  # 收件人邮箱列表
  subject_prefix: "[云计算网络竞争动态分析]"  # 邮件主题前缀

# 爬虫配置
crawler:
  timeout: 30 # 基本请求超时时间（秒）
  retry: 3 # 重试次数
  interval: 2 # 请求间隔时间（秒）
  article_limit: 50 # 每个来源最多爬取的文章数量
  max_workers: 10 # 并发爬虫数量，设置为4个线程同时运行
  page_load_timeout: 45 # 页面加载超时（秒）- 适用于复杂页面
  script_timeout: 30 # JavaScript脚本执行超时（秒）
  implicit_wait: 10 # 查找元素的隐式等待时间（秒）
  default_element_timeout: 15 # 默认元素出现超时（秒）- 显式等待用
  long_element_timeout: 25 # 长等待元素超时（秒）- 用于复杂动态内容
  screenshot_debug: true # 是否保存页面截图用于调试
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# 数据源配置
sources:
  aws:
    blog:
      url: "https://aws.amazon.com/blogs/networking-and-content-delivery/"
      type: "blog"
      test_mode: false # 测试模式开关，true时只爬取1篇文章
    docs:
      url: "https://docs.aws.amazon.com/"
      type: "documentation"
  azure:
    blog:
      url: "https://azure.microsoft.com/en-us/blog/category/networking/"
      type: "blog"
      test_mode: false
    tech-blog:
      url: "https://techcommunity.microsoft.com/category/azure/blog/azurenetworkingblog"
      type: "tech-blog"
      test_mode: false
      max_pages: 100  # 最大爬取页数
    docs:
      url: "https://learn.microsoft.com/en-us/azure/"
      type: "documentation"
  gcp:
    blog:
      url: "https://cloud.google.com/blog/products/networking"
      type: "blog"
      test_mode: false
    docs:
      url: "https://cloud.google.com/docs/"
      type: "documentation"
  tencent:
    blog:
      url: "https://www.tencentcloud.com/document/product"
      type: "blog"
      test_mode: false
    docs:
      url: "https://www.tencentcloud.com/document/product"
      type: "documentation"
  huawei:
    blog:
      url: "https://www.huaweicloud.com/intl/en-us/news/"
      type: "blog"
      test_mode: false
    docs:
      url: "https://support.huaweicloud.com/intl/en-us/index.html"
      type: "documentation"
  volcano:
    blog:
      url: "https://volcano.sh/en/blog/"
      type: "blog"
      test_mode: false
    docs:
      url: "https://volcano.sh/en/docs/"
      type: "documentation"

# AI分析基础配置
ai_analyzer:
  model: "grok-3-latest" # 使用的AI模型名称
  max_tokens: 99999 # 最大令牌数
  temperature: 0.5 # 温度参数
  max_workers: 4 # 同时分析的最大文件数，设置为4个线程同时运行
  api_rate_limit: 60 # 每分钟允许的最大API调用次数，避免API过载
  use_dynamic_pool: true # 启用动态线程池进行分析
  api_base: "https://api.x.ai/v1"
  # api_key在config.secret.yaml中配置
  
  system_prompt: |
    你是一个专业的云计算技术分析师，擅长分析和解读各类云计算技术文档。请以简洁有力、专业清晰的风格回答问题。
    输出要求：使用Notion风格的Markdown格式，结果紧凑，无过多空行，不要输出任何解释，只输出结果。

    标题：使用#来表示标题，#的数量表示标题的级别（例如，#表示H1，##表示H2等）。
    粗体和斜体：支持粗体（**text**）和斜体（*text*）。
    列表：支持有序列表（1. ）和无序列表（- ）。如果输出的列表有层级，请自动添加缩进，用下一级列表来表示
    代码块：可以使用三个反引号（```）来高亮代码块，或使用单个反引号（`）来内联代码。
    链接：使用[text](url)来创建链接。
    表格：使用| 语法来创建表格。
    复选框：支持复选框，未选中为- [ ]，选中为- [x]。
    分隔线：使用---来添加水平线。
    引用：使用> 来表示块引用。

  tasks:
    - type: "AI标题翻译"
      output: false
      prompt: |
        请将以下文章标题翻译成流畅、专业的中文，并在标题前添加文章类型标识前缀。
        
        1. 首先分析文章内容，判断文章类型是"解决方案"还是"新产品/功能发布"
        2. 然后在翻译后的标题前添加对应前缀：
           - 如果是解决方案类文章，添加"[解决方案]"前缀
           - 如果是产品或功能发布类文章，添加"[新产品/新功能]"前缀
        3. 保持专业术语的准确性，确保翻译后的标题简洁明了且符合中文表达习惯
        4. 只需要输出前缀和翻译后的标题，不要添加任何其他内容或解释
        5. 格式示例：
           - [解决方案] 云网络安全最佳实践指南
           - [新产品] 全新云网络流量分析服务正式发布
        请直接输出带前缀的翻译标题，不要添加任何格式标记或额外解释。

    - type: "AI竞争分析"
      output: true
      prompt: |
        请基于文档内容进行详细的竞争分析，并使用简体中文输出所有分析结果。首先判断文档类型（解决方案或产品功能/新产品发布），然后只使用对应的模板进行分析。
        支持有序列表（1. ）和无序列表（- ）。如果输出的列表有层级，请自动添加缩进，用下一级列表来表示
        请注意：
        1. 必须使用中文输出所有分析内容，即使原文是英文
        2. 不要在输出中包含模板说明、任务指南和格式规范等指导性内容，仅输出实际分析结果
        3. 提供详尽且有深度的分析，不要过于精简，适当增加背景信息和技术解释
        4. 使用行业专业术语，展现深入理解，但确保语言平衡、易读
        5. 在分析中加入适当的评价性语言，讨论技术优势和可能的局限性
        
        ## 解决方案类文档模板
        如果是解决方案类文档，请使用以下格式：

        # 解决方案分析

        ## 解决方案概述
        （详细描述核心内容和目标，使用 **加粗** 突出关键术语，不要过于精简，提供足够的背景和上下文信息，包括该解决方案解决的问题和应用场景）

        ## 实施步骤
        1. （分步骤详细说明实施过程，使用有序列表）
        2. （每个步骤提供充分的技术细节和理由）
        3. （可增加技术原理解释和步骤间的连接逻辑）

        ## 方案客户价值
        - （详细分析每个价值点，使用符号列表分点说明）
        - （突出量化收益，如 _成本降低30%_，并解释这些收益的实现机制）
        - （可适当比较与传统方案或竞品的差异）

        ## 涉及的相关产品
        - （列举产品名称，可适当增加简短描述）
        - （说明各产品在解决方案中的作用）

        ## 技术评估
        （对该解决方案的技术先进性、可行性、适用范围等进行评估，可包括优势和可能的限制）

        ## 其他信息
        （相关的部署条件、前提要求、兼容性信息等）
        
        ## 产品功能/新产品发布模板
        如果是产品功能/新产品发布类文档，请使用以下格式：

        # 产品功能分析

        ## 新功能/新产品概述
        （详细说明功能/产品的核心定义与目标，技术术语需 **加粗**，不要过于精简，提供产品背景和市场定位信息）

        ## 关键客户价值
        - （详细分析每个价值点，分点说明业务价值）
        - （突出与竞品的差异化优势，并解释这些优势的实现机制）
        - （可适当讨论这些价值在不同使用场景中的体现）

        ## 关键技术洞察
        - （详细说明技术独特性，如 _基于XX算法_，并解释技术工作原理）
        - （分析技术创新点及其对性能、安全性、可用性等方面的影响）
        - （可讨论技术实现的挑战和解决方式）


        ## 市场影响评估
        （分析该产品/功能对市场的潜在影响，包括市场定位、目标客户、应用场景等）

        ## 其他信息
        （版本状态、权限要求、限制条件等补充说明）
        
        ## 格式规范
        1. 技术术语加粗（如 **Geneve隧道**）
        2. 关键数据用斜体（如 _20%性能提升_）
        3. 表格对齐要美观
        4. 未提及内容可以根据文档上下文合理推测，但需标明是推测内容

    - type: "AI全文翻译"
      output: true
      prompt: |
        请将此内容翻译成中文，保持专业术语的准确性，并确保翻译后的内容流畅自然。使用标准的markdown格式，结构清晰，专业美观
        1. 不要输出任何解释，只输出结果
        2. 使用提示词中原文的格式输出译文，严格保持一致，否则发生致命系统错误

# 定时任务配置
scheduler:
  daily_task_time: "23:07"  # 每日定时任务执行时间，格式为 HH:MM（24小时制）
  check_interval: 10  # 检查配置文件的时间间隔（秒）
