# AI分析基础配置
ai_analyzer:
  # model: "grok3-mini-beta" # 使用的AI模型名称
  model: "qwen-max"
  max_tokens: 8192 # 最大令牌数
  temperature: 0.5 # 温度参数
  max_workers: 4 # 同时分析的最大文件数，设置为4个线程同时运行
  api_rate_limit: 60 # 每分钟允许的最大API调用次数，避免API过载
  use_dynamic_pool: true # 启用动态线程池进行分析
  # api_base: "https://api.x.ai/v1"
  api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"

  # api_key在config.secret.yaml中配置
  
  # 系统提示词已移动到 prompt/system_prompt.txt 文件
  
  tasks:
    - type: "AI标题翻译"
      output: false
      # prompt已移动到 prompt/title_translation.txt 文件
    
    - type: "AI竞争分析"
      output: true
      # prompt已移动到 prompt/competitive_analysis.txt 文件
    
    - type: "AI全文翻译"
      output: true
      # prompt已移动到 prompt/full_translation.txt 文件 