# 爬虫配置
crawler:
  timeout: 30  # 请求超时时间（秒）
  retry: 3     # 重试次数
  interval: 2  # 请求间隔时间（秒）
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# 数据源配置
sources:
  aws:
    blog: 
      url: "https://aws.amazon.com/blogs/networking-and-content-delivery/"
      type: "blog"
    docs:
      url: "https://docs.aws.amazon.com/"
      type: "documentation"
  azure:
    blog:
      url: "https://azure.microsoft.com/en-us/blog/"
      type: "blog"
    docs:
      url: "https://learn.microsoft.com/en-us/azure/"
      type: "documentation"
  gcp:
    blog:
      url: "https://cloud.google.com/blog/"
      type: "blog"
    docs:
      url: "https://cloud.google.com/docs/"
      type: "documentation"

# AI分析配置 - 阿里云通义千问配置示例
ai_analyzer:
  model: "qwen-max"                  # 使用的通义千问模型
  max_tokens: 4000                   # 最大令牌数
  temperature: 0.8                   # 温度参数
  api_key: ""                        # 在此处填写您的阿里云API密钥
  api_base: "https://dashscope.aliyuncs.com/v1"  # 阿里云通义千问API基础URL
  system_prompt: "你是一个专业的云计算技术分析师，擅长分析和解读各类云计算技术文档。请以简洁有力、专业清晰的风格回答问题。" # 系统提示词
  tasks:
    - type: "summary"
      prompt: "请对此云服务商的内容进行总结，突出主要功能、优势和技术特点。总结控制在300字以内，要点清晰。"
    - type: "translation"
      prompt: "请将此内容翻译成中文，保持专业术语的准确性，并确保翻译后的内容流畅自然。"
    - type: "comparison"
      prompt: "请分析此服务与其他云服务商类似服务的区别和竞争优势。重点关注技术创新点、性能指标、成本效益和适用场景等方面。分析要有理有据，言之有物。" 